import type {Metadata} from "next";
import "./globals.css";
import {lato, newsreader, pt_sans} from "@/app/fonts";
import TopNav from "@/app/components/TopNav";
import Footer from "@/app/components/Footer";


export const metadata: Metadata = {
    title: "Western Dakota Regional Water System",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${newsreader.variable} ${lato.variable} ${pt_sans.variable} overflow-x-hidden`}>
        <TopNav/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}
